# Generated by Django 3.1.2 on 2020-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default="Hi! It's a lovely day", max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.TextField(default='https://www.flaticon.com/svg/static/icons/svg/847/847969.svg', max_length=200),
        ),
    ]
