# Generated by Django 3.1.2 on 2020-10-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201012_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
