# Generated by Django 3.1.1 on 2020-10-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201002_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default="Hi! It's a lovely day"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.TextField(default='https://www.flaticon.com/svg/static/icons/svg/847/847969.svg'),
        ),
    ]
